
name: S3 Push

on:
  push:
    branches: [ devel, workflows/add-client-build ]

jobs:
  s3-push-client:

    runs-on: ubuntu-latest
    needs: build-client

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: "index.html"
    - name: current-index-ptr
      run: |
        export DATENOW=$(date +%Y%m%d%H%M%s)
        echo $DATENOW
        echo "index-${DATENOW}.html" > current.txt
        cp "client/src/index.html" "index-${DATENOW}.html"
    - name: Upload current file to S3 bucket
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl private
      env:
        FILE: current.txt
        AWS_REGION: 'us-west-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload index to S3 bucket
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl private
      env:
        FILE: "index-*.html"
        AWS_REGION: 'us-west-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
